main: me.metumortis.joinquitmessages.JoinQuitMessages
name: JoinQuitMessages
author: MetuMortis
api-version: 1.18
version: 1.0
commands:
  joinquitmessages:
    description: "Main command"
    usage: /joinquitmessages
    aliases:
      - jqm