/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.metumortis.joinquitmessages
import me.metumortis.joinquitmessages.eventhandlers.Join
import me.metumortis.joinquitmessages.eventhandlers.Quit
import org.bukkit.ChatColor
import org.bukkit.Material
import org.bukkit.event.player.PlayerJoinEvent
import org.bukkit.plugin.java.JavaPlugin
class JoinQuitMessages : JavaPlugin() {

    override fun onEnable(){
        logger.warning("Activated")
        saveDefaultConfig()
        reloadConfig()
        server.pluginManager.registerEvents(Join(this), this)
        server.pluginManager.registerEvents(Quit(this), this)
        getCommand("joinquitmessages")!!.setExecutor(ReloadHandler(this))
    }


    companion object{
        fun translateColors(str: String): String {
            if("&#[0-9a-f]{6}".toRegex().containsMatchIn(str)){
                var parsedStr = str
                //println(str.replace("&#([0-9a-f]{6})".toRegex(), "\u00A7$1"));
                for (x in "&(#[0-9A-f]{6})".toRegex().findAll(str)){
                    parsedStr = parsedStr.replaceFirst(x.value.toRegex(), net.md_5.bungee.api.ChatColor.of(x.value.slice(
                        1 until x.value.length
                    )).toString())
                }
                return ChatColor.translateAlternateColorCodes('&', parsedStr)
            }
            return ChatColor.translateAlternateColorCodes('&', str)
        }
    }
}

fun main() {
    println("Hi")
}
